### ISSUE TITLE
Silex 2 Support

### ISSUE THREAD

**Issue by batwolf** [thecodingmachine/silex-middleware#1]
Hi, thanks for your software :) Any idea when Silex 2 support will be available?

**Comment by moufmouf** [comment]
Hey @batwolf ,

It's pretty unlikely we will evolve this package with Silex 2 support.
Indeed, we are now focusing on PSR-15 middlewares (middlewares based on the PSR-7 request/response objects) and not so much on StackPHP middlewares anymore.

Yet, if you need this, it should be pretty easy to add Silex 2 support to this middleware. If you want to give it a try, I'd gladly accept a PR :)
